### ISSUE TITLE
As a user, I want to see the outcome results shown as percentages instead of fractions

### ISSUE THREAD

**Issue by mruissen** [tpcly/epsilon-lti#207]
## Acceptance criteria

 - [ ] Given `the graph bar` when `shows data`, then `the corresponding result should be in percentages`.

![Schermafbeelding 2023-12-20 om 12 07 02](https://github.com/tpcly/epsilon-lti/assets/13045855/bb7bebdd-7411-4dfe-8620-0c1056d324c7)

## Checklist

Before creating a user story, make sure you have given it the following:

 - [ ] **Milestone:** Sprint [x] (In most cases the current sprint)
 - [ ] **Importance:** Must / Should / Could / Would
 - [ ] **Item type:** User Story
 - [ ] **Priority:** Very High / High / Medium / Low

Make sure you **DON'T** fill in the "Effort" tag, since that is to be decided during a SCRUM poker session.

**Comment by NealGeilen** [comment]
![image](https://github.com/tpcly/epsilon-lti/assets/44571222/b8bca7ed-8825-4b13-b19d-bca7fc4812a7)

**Comment by gmottajr** [comment]
Hi @NealGeilen,
I can help you out with that, please give me the details so that I can start work on a change following your specification. 
 Appreciate your guidance over this matter, 
thank you very much!
