### ISSUE TITLE
As a team, we need to rewrite the competence document creation process in the backend so that it aligns seamlessly with the new data structure

### ISSUE THREAD

**Issue by jendafojtik** [tpcly/epsilon-lti#35]
- [ ] Setup document creation
- [ ] Rewrite competence matrix
- [ ] Rewrite KpiMatrixCollection

**Comment by NealGeilen** [comment]
The following issue will be closed. Because the scope is too big for a single issue. 

It will be separated in #58 #57 #56 and #55
