### ISSUE TITLE
Fontys Git connection 

### ISSUE THREAD

**Issue by NealGeilen** [tpcly/epsilon-lti#37]
Fontys requires that all material that is created also is located on the school Git platform. 

Therefore there will needs to be a connection with the School Git so that students can deliver their work. 

This will be in the form of a GitHub action that will trigger a copy of pushes to a repository of school

**Comment by jendafojtik** [comment]
@NealGeilen please add a time estimate so that I can later do a better analysis of how much work we've burned in a sprint
