### ISSUE TITLE
Bug `feature` is not working

### ISSUE THREAD

**Issue by mruissen** [tpcly/epsilon-lti#726]
# What is not working?

New P.D. comptences are not showing in the graphs

<img width="1001" alt="Screenshot 2024-11-13 at 14 32 12" src="https://github.com/user-attachments/assets/8f2f7906-1e5f-4404-8b43-16e804d1c569">

---

# What is the result that you needed? 

That the new P.D. comptences show up in the graph.

---

# What are the steps that you took before you noticed the bug? 

Upon opening a new student with the new set of competences.

---

**Comment by NealGeilen** [comment]
The bug is solved, was caused by an error in production database.
